myproject/urls.py
from django.urls import path
from . import views

app_name = 'myproject'

urlpatterns = [
    path('', views.home, name='home'),
    path('profile/', views.profile, name='profile'),
    path('about-me/', views.about, name='about'),
    path('contacts/', views.contacts, name='contacts'),
	path('events/', views.list, name='schedule'),
	path('delete/(?P<delete_id>[0-9]+)', views.delete, name='delete'),
	path('events/add-event/', views.create, name='event'),
]

story4/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myproject.urls')),
]

myproject/models.py
from django.db import models

# Create your models here.

class Schedule(models.Model):
	name = models.CharField(max_length=100)
	date = models.DateTimeField(("Date & Time"), auto_now_add=False)
	place = models.CharField(max_length=100)
	LIST_CATEGORY = (
		('Assignment','Assignment'),
		('Class','Class'),
		('Committee Work','Committee Work'),
		('Daily Work','Daily Work'),
		('Organization','Organization'),
		('Quiz','Quiz')
	)
	category = models.CharField(
		max_length=100, choices = LIST_CATEGORY,
		default = 'Assignment'
	)
	notes = models.TextField(blank = True)
	
	def __str__(self):
		return "{}.{}".format(self.id, self.name)

myproject/forms.py
from django import forms
from .models import Schedule

class ScheduleForm(forms.ModelForm):
	class Meta:
		model = Schedule
		fields = [
			'name',
			'date',
			'place',
			'category',
			'notes'
		]
		
		labels = {
			'name':'Event Name:',
			'date':'Date:',
			'place':'Place:',
			'category':'Category:',
			'notes':'Notes:'
		}
		
		widgets = {
			'name':forms.TextInput(
				attrs = {
					'class':'form-control',
					'placeholder':'fill with your event name'
				}
			),
			'date':forms.DateTimeInput(
				attrs = {
					'class':'form-control',
					'placeholder':'yyyy-mm-dd'
				}
			),
			'place':forms.TextInput(
				attrs = {
					'class':'form-control',
					'placeholder':'where the event takes place'
				}
			),
			'category':forms.Select(
				attrs = {
					'class':'form-control'
				}
			),
			'notes':forms.Textarea(
				attrs = {
					'class':'form-control'
				}
			)
		}

myproject/views.py
from django.shortcuts import render, redirect
from .forms import ScheduleForm
from .models import Schedule 
# Create your views here.

def list(request):
	posts = Schedule.objects.all()
	
	context = {
		'page_title' : 'My Schedule',
		'posts':posts,
	}
	return render(request, 'list.html', context)
	
def delete(request, delete_id):
	Schedule.objects.filter(id=delete_id).delete()
	return redirect('myproject:schedule')
	
def create(request):
	sched_form = ScheduleForm(request.POST or None)
	if request.method == 'POST':
		if sched_form.is_valid():
			sched_form.save()
			return redirect('myproject:schedule')

	context = {
		'page_title' : 'Add Event',
		'sched_form':sched_form,
	}
	return render(request, 'create.html', context)
	
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def profile(request):
    return render(request, 'profile.html')
	
def contacts(request):
    return render(request, 'contacts.html')

myproject/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
	<head>
		<title>ABOUT ME</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	</head>
	
	<body>
	
		<div class="container2">
			<div class="row">
				<div class="col-md-4">
					<img src="{% static 'images/scenery.jpg' %}" id="scenery"/>
					<h2 id="quote"><strong>I Like to be Adventurous<br>
						& See the World Through<br>Various Perspectives</strong></h2>
				</div>
				<div class="col-md-4">
					<div class="col">
						<div class="row-md-2">
							<h3 id="dedicate"><strong>&#128154 I Am a Dedicated Person.</strong></h3>
							<p class="dedicate-desc">I'm a highly dedicated person. I sometimes even
							risk my health to finish the job I am responsible of. It's very important
							for me to dedicate myself to do something I am responsible of for the sake of
							common goods.</p>
						</div>
						<div class="row-md-2">
							<h3 id="environment"><strong>&#127759 I Am an Environmentalist.</strong></h3>
							<p class="env-desc">When you claim yourself as an environmantalist,
							you need to be truly care about the environment and start by doing
							some little and meaningful things to save the earth!</p>
						</div> 
						<div class="row-md-2">
							<h3 id="creativity"><strong>&#128444 I Express My Creativity Through Designs.</strong></h3>
							<p class="creativity-desc">I've been into designs since
								I was a sophomore in high school. And since I also study
								computer science, I'm aspired to put my sense of aesthetic-ness
								into digital product designs.</p> 
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<div class="col">
						<div class="row-md-2">
							<h3 id="music"><strong>&#127926 I Love Alternative Musics.</strong></h3>
							<p class="music-desc">I love alternative/indie and RnB musics. Yes, my music taste is
							a little bit anti-mainstream. My favourite kind of bands/musicians are something like
							LANY, Honne, The 1975, The Japanese House, Girl in Red, Declan McKenna, Frank Ocean, SZA,
							Alextbh, etc.</p>
						</div>
						<div class="row-md-2">
							<h3 id="travel"><strong>&#9992 I Like to Travel.</strong></h3>
							<p class="travel-desc">Travelling could be very exciting for me.
							I could bump into my peace of mind. Besides that,
							going back to nature can make me learn to appreciate life more by
							seeing the world from different perspectives.</p>
						</div> 
						<div class="row-md-2">
							<h3 id="horror"><strong>&#128123 I Am Into Horror Stuff.</strong></h3>
							<p class="horror-desc">Meanwhile most of my friends find horror/thriller stuff,
							such as horror/thriller movies, books, or short story scary, I find them
							intriguing! It's always exciting for me to read horror stories,
							especially the ones that are based on true events like Cermis UI.</p> 
						</div>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>

{% endblock %}

myproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	</head>
  <body>
    <div class="bg-shape"></div>
	<nav class="navbar navbar-light">
		<ul class="nav nav-pills">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'myproject:home' %}">HOME</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'myproject:about' %}">ABOUT ME</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'myproject:profile' %}">MY PROFILE</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'myproject:schedule' %}">EVENTS</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'admin:index' %}">ADMIN</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'myproject:contacts' %}">CONTACTS</a>
			</li>
		</ul>
	</nav>
    {% block content %}
	{% endblock %}
  </body>
</html>

myproject/templates/contacts.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
	<head>
		<title>CONTACT ME</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	</head>
	
	<body>
	
		<div class="container4">		
			<div class="row">
				<div class="col-md-6" style="height: 560px">
					<h1 id="text">Let's Get in Touch!<br>Find Me on:</h1>
				</div>
				<div class="col-sm-6" style="height: 560px">
					<div class="components">
						<p><a href="https://www.linkedin.com/in/kirana-alfatianisa-1b2852185/" target="_blank"><img alt="linkedin" style="vertical-align: middle;
						margin-left: 12px; height:70px" src="{% static 'images/linkedin.png' %}"/><span style="font-size: 28px; margin-left: 12px">Kirana Alfatianisa</span></a></p>
						<p><a href="https://instagram.com/kiralft" target="_blank"><img alt="insta" style="vertical-align: middle; margin-left: 11px; height:70px"
						src="{% static 'images/instagram.png' %}"/><span style="font-size: 28px; margin-left: 13px">kiralft</span></a></p>
						<p><a href="mailto: alfatianisa@gmail.com" target="_blank"><img alt="gmail" style="vertical-align: middle; height:70px; margin-left: 12px"
						src="{% static 'images/mail.png' %}"/><span style="font-size: 28px; margin-left: 12px">alfatianisa@gmail.com</span></a></p>
					</div>
				</div>
			</div>
			<div class="row-md-1">
				<h3 id="copyright"><strong>Kirana Alfatianisa &copy 2019</strong></h3>
			</div>
		</div>
	</body>
</html>

{% endblock %}

myproject/templates/create.html
{% extends 'base.html' %} 
{% load static %}
{% block content %}
<!DOCTYPE html>
<html>
	<head>
		<title>HOME</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	</head>
	
	<body>
		<div class = "col">
			<div class="row">
				<h1 class="add-title">{{page_title}}</h1>
			</div>
				<div class="row">
					<div class="col-md-8" style="height: 560px">
						<form class="needs-validation" novalidate id="formulir" method='POST'>
							{% csrf_token%}
							{% for form in sched_form %}
							<div class="form-group">
								{{form.label}}
								{{form}}
								<div class="valid-feedback">
									Looks good!
								</div>
								<div class="invalid-feedback">
									This field is required.
								</div>
							</div>
							{% endfor %}
							<button class='btn btn-primary' type="Submit">Add Event</button>
						</form>
						<script>
(function() {
  'use strict';
  window.addEventListener('load', function() {
    // Fetch all the forms we want to apply custom Bootstrap validation styles to
    var forms = document.getElementsByClassName('needs-validation');
    // Loop over them and prevent submission
    var validation = Array.prototype.filter.call(forms, function(form) {
      form.addEventListener('submit', function(event) {
        if (form.checkValidity() === false) {
          event.preventDefault();
          event.stopPropagation();
        }
        form.classList.add('was-validated');
      }, false);
    });
  }, false);
})();
</script>
					</div>
				</div>
		</div>
	</body>
</html>

{% endblock %}
 
 

myproject/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
	<head>
		<title>HOME</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	</head>
	
	<body>

		<div class = "container">
			<div class="row">
				<div class="col-sm-7">
					<h1 id="hello"><strong>HELLO!&#x1f44b </strong><br>My Name is<br>Kirana Alfatianisa.</h1>
					<p id="desc">I'm a graphic and web design enthusiast.<br> I'm currently in my sophomore year of studying computer<br>
						science at University of Indonesia and really aspired to be a<br>
						front end developer or data analyst in the near future!</p>
				</div>
				<div class="col-sm-5">
					<img src="{% static 'images/me.jpg' %}" alt="self picture" id="mypic"/>
				</div>
			</div>
		</div>
	</body>
</html>

{% endblock %}

myproject/templates/list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
	<head>
		<title>MY SCHEDULE</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	</head>
	
	<body>
		<div>
			<h1 class="ev-title"><strong>My Events</strong></h1>
		</div>
		<div class="table-responsive">
			<table class="table table-hover">
				<thead>
					<tr>
						<th scope="col" id="head">#</th>
						<th scope="col" id="head">Event</th>
						<th scope="col" id="head">Date</th>
						<th scope="col" id="head">Place</th>
						<th scope="col" id="head">Category</th>
						<th scope="col" id="head">Note</th>
						<th scope="col" id="head">Delete</th>
					</tr>
				</thead>
  
				<tbody>
					{% for post in posts%}
					<tr class = "success">
						<th scope="row" id="head">{{forloop.counter}}</th>
						<td>{{post.name}}</td>
						<td>{{post.date}}</td>
						<td>{{post.place}}</td>
						<td>{{post.category}}</td>
						<td>{{post.notes}}</td>
						<td><a class="btn btn-light" href="{% url 'myproject:delete' post.id %}" title="">&#128465</a></td>
					</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
		<div class = "tombol">
			<a class="btn btn-primary" href="{% url 'myproject:event' %}" role="button">Add New Event</a>
		</div>
	</body>
</html>
{% endblock %}

myproject/templates/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!DOCTYPE html>
<html>
	<head>
		<title>MY PROFILE</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
	</head>
	
	<body>
	
		<div class="container3">
			<div class="row">
				<div class="col-md-5">
					<div id="headd">
						<h1 id="name"><strong>Kirana Alfatianisa</strong></h1>
						<h3 id="date">Sophomore at University of Indonesia<br>
						Born in Jakarta, August 12, 2000</h3>
						<h2 id="dots"> .               .               .    </h2>
					</div>
				</div>
				<div class="col-md-7">
					<h2 class="emojis">&#127891  &#127942  &#128203  &#9881</h2>
				</div>
			</div>

			<div class="row">
				<div class="col-md-4">
					<div class="col">
						<div class="row-md-6">
							<h2 id="ed">Educations:</h2>
							<ul class="educations">
								<li class="edu">
									<p>SD Negeri Cipedak 03 (2006-2012)</p>
								</li>
								<li class="edu">
									<p>SMP Negeri 85 Jakarta (2012-2015)</p>
								</li>
								<li class="edu">
									<p>SMA Negeri 28 Jakarta (2015-2018)</p>
								</li>
								<li class="edu">
									<p>Faculty of Computer Science,
									University of Indonesia (2018-now)</p>
								</li>
							</ul>
						</div>
						<div class="row-md-6">
							<h2 id="ach">Achievements:</h2>
							<ul class="achievements">
								<li class="achv">
									<p>2nd Place at 8 Research Competition (2016)</p>
								</li>
								<li class="achv">
									<p>2nd Runner Up at KIR Jakarta Selatan Research Paper Competition (2016)</p>
								</li>
							</ul>
						</div>
					</div>
				</div>
				<div class="col-md-4">
					<h2 id="exp">Experiences:</h2>
					<ul class="experiences">
						<li class="expr">
							<p>Creative & Documentation Staff of Science Class SMAN 28 Jakarta (2015)</p>
						</li>
						<li class="expr">
							<p>PIC of Design & Decoration at Science Class SMAN 28 Jakarta (2016)</p>
						</li>
						<li class="expr">
							<p>PIC of Science Project Competition at Robotic Day (2017)</p>
						</li>
						<li class="expr">
							<p>Deputy of Technological Applications at KIR SMAN 28 Jakarta (2016-2017)</p>
						</li>
						<li class="expr">
							<p>Liaison Officer at OIM UI 2018 (2018)</p>
						</li>
						<li class="expr">
							<p>Secretary Staff at COMPFEST 11 (2019)</p>
						</li>
						<li class="expr">
							<p>Staff of Entrepreneurship Division at DPM Fasilkom UI</p>
						</li>
					</ul>
				</div>
				<div class="col-md-4">
					 <h2 id="skills">Skills & Tools:</h2>
					<ul class="skill-lst">
						<li class="sk">
							<p>Java</p>
						</li>
						<li class="sk">
							<p>Python 3</p>
						</li>
						<li class="sk">
							<p>HTML 5</p>
						</li>
						<li class="sk">
							<p>CSS</p>
						</li>
						<li class="sk">
							<p>Canva</p>
						</li>
						<li class="sk">
							<p>Power BI</p>
						</li>
						<li class="sk">
							<p>Microsoft Office</p>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</body>
</html>

{% endblock %}